In [1]:
import pandas as pd
import numpy as np
import ast
import re

In [25]:
unique_slugs_df = pd.read_csv('unique_slugs_df.csv')
unique_slugs_df.shape

(728, 2)

In [4]:
old_site_p = pd.read_csv('old_site_products.csv')
new_site_p = pd.read_csv('new_site_products.csv')

In [15]:
cols_to_keep = ['id', 'name', 'brand', 'main_category', 'categories', 'slug']
old_site_p = old_site_p[cols_to_keep]
old_site_p.shape

(761, 6)

In [17]:
cols_to_keep = ['id', 'name', 'brand', 'main_category', 'categories', 'slug']
new_site_p = new_site_p[cols_to_keep]
new_site_p.shape

(688, 6)

In [5]:
old_slug_to_id = dict(zip(old_site_p['slug'], old_site_p['id']))
new_slug_to_id = dict(zip(new_site_p['slug'], new_site_p['id']))

In [53]:
df = pd.concat([old_site_p, new_site_p])
df.shape

(1449, 6)

In [54]:
unified_catalog = pd.read_csv('unified_catalog.csv')
unified_catalog.dtypes

Unnamed: 0        int64
id                int64
name             object
brand            object
main_category    object
categories       object
slug             object
dtype: object

In [59]:
# df['categories'] = df['categories'].apply(ast.literal_eval)

In [62]:
# for idx,row in df.iterrows():
#     new_cats = []
#     for cat in row['categories']:
#         if cat != row['main_category']:
#             new_cats.append(cat)
#     df.at[idx,'categories'] = new_cats

df['categories'] = df.apply(
    lambda row: [cat for cat in row['categories'] if cat != row['main_category']], 
    axis=1
)

TypeError: 'float' object is not iterable

In [42]:
uniq_names = list(df['name'].unique())
name_rus_to_eng = {}

for idx,name in enumerate(uniq_names):
    print(f'Done till {idx}')
    try:
        eng_name = translator.translate(name)
        name_rus_to_eng[name] = eng_name
    except Exception as e:
        print(f'No translation for name: {name}')
        name_rus_to_eng[name] = 'No_translation'

Done till 0
No translation for name: Автокресло Baby Care BSO Sport Isofix
Done till 1
No translation for name: Автокресло Chicco Key1 X-Plus ISOFIX
Done till 2
No translation for name: Автокресло Chicco Synthesis XT-Plus
Done till 3
No translation for name: Дом-палатка с туннелем «Океан»
Done till 4
No translation for name: Барабан для малышей
Done till 5
No translation for name: Автокресло Chicco Oasys 2-3
Done till 6
No translation for name: Автокресло Chicco Xpace Isofix
Done till 7
No translation for name: Автокресло Chicco Go-One
Done till 8
No translation for name: Автокресло Maxi-Cosi CabrioFix
Done till 9
No translation for name: Автокресло Britax Romer KING II
Done till 10
No translation for name: Дом-палатка «Жирафик»
Done till 11
No translation for name: Динозавр с шариками
Done till 12
No translation for name: Ведерко Maxi Bloks
Done till 13
No translation for name: Аквариум-сортер
Done till 14
No translation for name: Электронные качели MamaRoo 4.0
Done till 15
No translation for name: Автокресло Britax Romer KIDFIX XP
Done till 16
No translation for name: Автокресло Chicco Youniverse
Done till 17
No translation for name: Автокресло Chicco Eletta Comfort
Done till 18
No translation for name: Коляска-трость Maclaren Quest
Done till 19
No translation for name: Детские кресла
Done till 20
No translation for name: Коляска детская Nike
Done till 21
No translation for name: Дом-палатка с туннелем
Done till 22
No translation for name: Автокресло Cam Gara New
Done till 23
No translation for name: Батут Baby Fitness Imaginarium
Done till 24
No translation for name: Автокресло Chicco Key1 X-Plus
Done till 25
No translation for name: Автовоз Oball
Done till 26
No translation for name: Автокресло Primo Viaggio DUO-FIX
Done till 27
No translation for name: Коляска-трость Maclaren Triumph
Done till 28
No translation for name: Игровой домик Бабочки (конус)
Done till 29
No translation for name: Автокресло Maxi-Cosi Pebble
Done till 30
No translation for name: Автокресло Happy Baby Atlant
Done till 31
No translation for name: Автокресло Geoby CS888
Done till 32
No translation for name: Автокресло Chicco Quasar Plus Astral
Done till 33
No translation for name: Электронные качели MamaRoo 3.0
Done till 34
No translation for name: Автокресло Chicco Neptune
Done till 35
No translation for name: Автокресло Chicco Cosmos
Done till 36
No translation for name: Автокресло Chicco Auto-Fix Fast Baby
Done till 37
No translation for name: самокат
Done till 38
No translation for name: Беговел Puky LR 1 EVA
Done till 39
No translation for name: Большой электронный мат «Пианино»
Done till 40
No translation for name: Автомобиль «Безумные гонки»
Done till 41
No translation for name: Автокресло Siger Стар Isofix
Done till 42
No translation for name: Беговел Puky LR M
Done till 43
No translation for name: Активная игрушка «Треугольник»
Done till 44
No translation for name: Барабанная установка «Суперзвезда» Winfun
Done till 45
No translation for name: Активный игровой столик 5-в-1
Done till 46
No translation for name: Шезлонг «Любимый зоопарк» Fisher Price
Done till 47
No translation for name: Большой динозавр с шариками
Done till 48
No translation for name: Деревянная игрушка «Ноев Ковчег» ELC
Done till 49
No translation for name: Веревочная лестница к ДСК «Ранний старт»
Done till 50
No translation for name: Барабаны-бонго для купания
Done till 51
No translation for name: Гимнастический комплекс Chicco
Done till 52
No translation for name: Автомобильная горка «Чудеса на виражах»
Done till 53
No translation for name: Аккордеон Imaginarium
Done till 54
No translation for name: Кубики со звуком
Done till 55
No translation for name: Кресло-качалка «Друзья из тропического леса»
Done till 56
No translation for name: Гусеничная горка ELC
Done till 57
No translation for name: Автокресло Sparco F500K
Done till 58
No translation for name: Логическая игрушка-сортер "Фигуры"
Done till 59
No translation for name: Активная пирамидка
Done till 60
No translation for name: Активный центр «Кружись, играя!»
Done till 61
No translation for name: Видеоняня Philips Avent SCD 603
Done till 62
No translation for name: Вертолёт "Скорая помощь"
Done till 63
No translation for name: Сортер-пирамидка Радужные блоки
Done till 64
No translation for name: Батут для малышей «Жираф»
Done till 65
No translation for name: Активная игра для малыша «Домик»
Done till 66
No translation for name: Говорящий крот
Done till 67
No translation for name: Большой детский манеж Shell
Done till 68
No translation for name: Тележка с кубиками ELC
Done till 69
No translation for name: Автокресло Siger Кокон
Done till 70
No translation for name: Автокресло Siger Эгида Люкс
Done till 71
No translation for name: Большой автовоз с машинками Little Tikes
Done till 72
No translation for name: Беговел Puky Wutsch
Done till 73
No translation for name: Интерактивный стол Vtech "Играй и Учись"
Done till 74
No translation for name: Амбар с замочками
Done till 75
No translation for name: Барабан «Король Лев»
Done till 76
No translation for name: Сортер по весу Weight Cylinders
Done till 77
No translation for name: Беговел «Run Ride»
Done till 78
No translation for name: Автокресло Sparco F1000K
Done till 79
No translation for name: Автокресло Siger Бустер FIX
Done till 80
No translation for name: Беговел Strider 12 Classic
Done till 81
No translation for name: Игрушка для малышей «Жираф»
Done till 82
No translation for name: Весёлая горка для Yo-Yo Fisher Price
Done till 83
No translation for name: Автокресло Siger Кокон Isofix
Done till 84
No translation for name: Автолюлька Concord Air.Safe
Done till 85
No translation for name: Боулинг с животными Африки Vtech
Done till 86
No translation for name: Активный сортер
Done till 87
No translation for name: Беговел Chillafish Bunzi
Done till 88
No translation for name: Двусторонний кубик
Done till 89
No translation for name: Беговел Puky Pukylino
Done till 90
No translation for name: Аккордеон Vtech
Done till 91
No translation for name: Морской лев музыкальный
Done till 92
No translation for name: Автолюлька Chicco Keyfit 30
Done till 93
No translation for name: Автокресло Primo Viaggio Surefix
Done till 94
No translation for name: Самосвал ECOLINE MIDI
Done till 95
No translation for name: Беговел Janod
Done till 96
No translation for name: Автокресло Sparco F700K
Done till 97
No translation for name: Пожарная машина MIGHTY
Done till 98
No translation for name: Деревянная головоломка Hape
Done till 99
No translation for name: Аккордеон Janod
Done till 100
No translation for name: Автокресло Siger Стар
Done till 101
No translation for name: Весы LAICA PS 3001
Done till 102
No translation for name: Весы LAICA PS 3003
Done till 103
No translation for name: Горка удлиненная KIDWOOD
Done till 104
No translation for name: Двуязычный ноутбук  «Смейся и учись!»
Done till 105
No translation for name: Гамак-кроватка KIDWOOD
Done till 106
No translation for name: Видеоняня Maman VB603
Done till 107
No translation for name: Горка KIDWOOD
Done till 108
No translation for name: Гимнастическая трапеция к ДСК «Ранний старт»
Done till 109
No translation for name: Видеоняня Motorola MBP33
Done till 110
No translation for name: Весы LAICA MD 6141
Done till 111
No translation for name: Игровой набор "Кофемашина"
Done till 112
No translation for name: Говорящая ферма Chicco
Done till 113
No translation for name: Видеоняня Motorola MBP28
Done till 114
No translation for name: Деревянная игрушка-ходунок «Верстак»
Done till 115
No translation for name: Игровой набор "Печь"
Done till 116
No translation for name: Говорящий руль Chicco
Done till 117
No translation for name: Гараж 3х уровневый Viking City
Done till 118
No translation for name: Горка «Тачки»
Done till 119
No translation for name: Гитара Chicco
Done till 120
No translation for name: Весы Maman SBBC 212
Done till 121
No translation for name: Гоночный серпантин с машинками, Fisher Price
Done till 122
No translation for name: Говорящий дракон
Done till 123
No translation for name: Горка "Заяц" без баскетбольного кольца
Done till 124
No translation for name: Игровой набор "Весы"
Done till 125
No translation for name: Говорящий жук
Done till 126
No translation for name: Говорящий столик Chicco
Done till 127
No translation for name: Гонки ELC
Done till 128
No translation for name: Гараж с машинками ELC
Done till 129
No translation for name: Видеоняня Maman BM3200
Done till 130
No translation for name: Весы Maman SBBC 216
Done till 131
No translation for name: Гараж 2х уровневый Viking City
Done till 132
No translation for name: Гоночный трек с батутом Oball
Done till 133
No translation for name: Веселый паровозик с мячиками
Done till 134
No translation for name: Говорящий видеотелефон (рус/англ)
Done till 135
No translation for name: Деревянная игрушка-ходунок «Кухня»
Done till 136
No translation for name: Двусторонний развивающий центр
Done till 137
No translation for name: Вкладыш для новорожденных MamaRoo
Done till 138
No translation for name: Деревянная каталка «Белка»
Done till 139
No translation for name: Весы Maman SBBC217
Done till 140
No translation for name: Говорящий куб Chicco
Done till 141
No translation for name: Говорящая тележка для покупок
Done till 142
No translation for name: Грузовик «King»
Done till 143
No translation for name: Видеоняня Motorola MBP36
Done till 144
No translation for name: Гоночный трек ELC
Done till 145
No translation for name: Игровой домик Бабочки (квадрат)
Done till 146
No translation for name: Весы Maman SBBC 215
Done till 147
No translation for name: Горка для малышей StarPlast
Done till 148
No translation for name: Груша боксерская к ДСК «Ранний старт»
Done till 149
No translation for name: Детский велосипед 14 DRAGON B'TWIN
Done till 150
No translation for name: ДСК "Богатырь" с горкой
Done till 151
No translation for name: Деревянный игровой комплекс Берёзка
Done till 152
No translation for name: Детский коврик Bubble "Кактусы/Клетка"
Done till 153
No translation for name: Деревянные ходунки 2-в-1
Done till 154
No translation for name: Кубик для игр «Веселые животные»
Done till 155
No translation for name: Детская горка «Funny Slide»
Done till 156
No translation for name: Деревянная каталка «Зайчик»
Done till 157
No translation for name: Игровая панель «Щенок на паровозике»
Done till 158
No translation for name: ДСК «Ранний старт» люкс полная комплектация
Done till 159
No translation for name: Деревянный центр «Домик Макса»
Done till 160
No translation for name: Игровой набор "Чудо-Ферма"
Done till 161
No translation for name: Детская горка Marian Plast
Done till 162
No translation for name: Деревянный музыкальный набор Hape
Done till 163
No translation for name: Домик-сортер «Лес»
Done till 164
No translation for name: Детская качалка "Лошадка"
Done till 165
No translation for name: Детская горка «Слоник» с баскетбольным кольцом
Done till 166
No translation for name: Детский коврик Bubble "На опушке"
Done till 167
No translation for name: Креслице-качалка «Львёнок», Lider Kids
Done till 168
No translation for name: Домик «Белоснежка и семь гномов»
Done till 169
No translation for name: Дом-палатка «Царевна-лягушка»
Done till 170
No translation for name: Деревянная развивающая игрушка «Ковчег»
Done till 171
No translation for name: Детский манеж Natural
Done till 172
No translation for name: Детская горка «Заяц» с баскетбольным кольцом
Done till 173
No translation for name: Креслице-качалка «Мишка Тедди», Lider Kids
Done till 174
No translation for name: Единорог "Шагаю и повторяю"
Done till 175
No translation for name: Деревянная каталка-сортер «Крокодил»
Done till 176
No translation for name: Кукольный домик с замочками
Done till 177
No translation for name: ДСК Ранний старт СТАНДАРТ (полная комплектация)
Done till 178
No translation for name: Детское велокресло Hamax Sleepy
Done till 179
No translation for name: Домашняя горка KAKA ROOF
Done till 180
No translation for name: Деревянный самокат
Done till 181
No translation for name: Деревянный гараж ELC
Done till 182
No translation for name: Домик для фей «Волшебное дерево»
Done till 183
No translation for name: Корабль с животными
Done till 184
No translation for name: Кроватка-манеж Chicco Zip&Go
Done till 185
No translation for name: Игрушка-стучалка "Катим шар"
Done till 186
No translation for name: Деревянная развивающая игрушка «Замок»
Done till 187
No translation for name: Детский манеж Deluxe Learning
Done till 188
No translation for name: Доска с замочками «Деревенский двор»
Done till 189
No translation for name: Деревянный лабиринт «Активный куб»
Done till 190
No translation for name: Игровой центр «Цветочная ферма»
Done till 191
No translation for name: Игровой центр ELC
Done till 192
No translation for name: Игровой деревянный столик ELC (большой)
Done till 193
No translation for name: Игровой центр «Мухоморчик»
Done till 194
No translation for name: Забавный жираф с машинками
Done till 195
No translation for name: Закусочная на колёсах Fisher Price
Done till 196
No translation for name: Игровой центр Bright Starts «Зоопарк 360»
Done till 197
No translation for name: Забавный слон-жонглер
Done till 198
No translation for name: Занимательная ферма
Done till 199
No translation for name: Игровой столик Weina
Done till 200
No translation for name: Игровой центр ExerSaucer «День на пляже»
Done till 201
No translation for name: Игровой центр «Футболист»
Done till 202
No translation for name: Игровой центр ExerSaucer «Дино»
Done till 203
No translation for name: Игровой столик с конструктором B Kids
Done till 204
No translation for name: Игровой центр 3-в-1 «Первооткрыватель»
Done till 205
No translation for name: Игрушка для создания мыльных пузырей «Лягушка»
Done till 206
No translation for name: Игровой центр ExerSaucer «Друзья из сафари»
Done till 207
No translation for name: Игровая панель «Друзья из тропического леса»
Done till 208
No translation for name: Игровой домик Yookidoo
Done till 209
No translation for name: Игровой центр «Первые уроки вождения»
Done till 210
No translation for name: Игровой набор «Мини Гольф Клуб»
Done till 211
No translation for name: Игровой набор Духовка LeapFrog
Done till 212
No translation for name: Игровой центр «Ползай вокруг» Fisher Price
Done till 213
No translation for name: Игровой центр ExerSaucer «Зоопарк»
Done till 214
No translation for name: Интерактивная игрушка Роккит и Спарки
Done till 215
No translation for name: Игровой столик Rock Band, Chicco
Done till 216
No translation for name: Игровой центр «Большой Автобус»
Done till 217
No translation for name: Ежик-аккордеон
Done till 218
No translation for name: Игровой стол с конструктором «Строй и учись»
Done till 219
No translation for name: Игровой центр "Баскетбольная лига"
Done till 220
No translation for name: Касса с экраном ELC
Done till 221
No translation for name: Каталка «Пожарная машина» Italtrike
Done till 222
No translation for name: Конструктор Trix-Track "Трек для малышей с мельницей"
Done till 223
No translation for name: Интерактивный робот Мови "Думай и учись"
Done till 224
No translation for name: Конструктор Trix-Track "Башня"
Done till 225
No translation for name: Игрушечное мини-пианино «Кот» с микрофоном
Done till 226
No translation for name: Игрушка к шезлонгу BabyBjorn «Летающие друзья»
Done till 227
No translation for name: Игрушка для ванны «Спасательный катер»
Done till 228
No translation for name: Игрушка из дерева «5 коробочек» I'm Toy
Done till 229
No translation for name: Каталка "Черепашка"
Done till 230
No translation for name: Интерактивный столик Kiddieland
Done till 231
No translation for name: Конструктор Trix-Track "Двойная дорожка"
Done till 232
No translation for name: Игрушка для купания «Крокодил на лодке»
Done till 233
No translation for name: Игровой чехол "Театр" для ДСК СТАНДАРТ и ЛЮКС
Done till 234
No translation for name: Каталка «Трамвай» Italtrike
Done till 235
No translation for name: Каталка «Водитель»
Done till 236
No translation for name: Игрушка для ванны «Подводная лодка»
Done till 237
No translation for name: Каталка «Лев» Italtrike
Done till 238
No translation for name: Каталка «Морские чудеса»
Done till 239
No translation for name: Игрушка для купания «Остров пузырьков»
Done till 240
No translation for name: Интерактивная игрушка "Фрэнки - Веселые ритмы"
Done till 241
No translation for name: Карета для фей
Done till 242
No translation for name: Игрушка музыкальная «Гитара» Battat
Done till 243
No translation for name: Игровой центр-ходунки 2-в-1 «Пингвин»
Done till 244
No translation for name: Игровой центр Weina «Радуга»
Done till 245
No translation for name: Карусель ELC
Done till 246
No translation for name: Каталка «Слоник» 3-в-1
Done till 247
No translation for name: Каталка «Деревянный фургон»
Done till 248
No translation for name: Интерактивный развивающий куб
Done till 249
No translation for name: Конструктор MegaBloks 80 деталей
Done till 250
No translation for name: Корабль «Веселый Роджер и Капитан Крюк»
Done till 251
No translation for name: Игрушка для купания «Фонтан с животными»
Done till 252
No translation for name: Игрушка «Светящийся глобус»
Done till 253
No translation for name: Игрушка Vtech Водитель Рули и учись
Done till 254
No translation for name: Качели-колыбель «Умные и бесшумные»
Done till 255
No translation for name: Коляска прогулочная UPPAbaby Cruz 2018
Done till 256
No translation for name: Коляска-трость FD-Design Amigo Street
Done till 257
No translation for name: Каталка-игровой центр 2-в-1 «Симфония»
Done till 258
No translation for name: Коврик с интерактивным столиком Lorelli Toys
Done till 259
No translation for name: Каталка с конструктором 3-в-1
Done till 260
No translation for name: Кораблик с игрушками для ванны Battat
Done till 261
No translation for name: Качели TAKO
Done till 262
No translation for name: Качели электронные «Комфорт и гармония»
Done till 263
No translation for name: Каталка Mega Bloks Jeep 3-в-1
Done till 264
No translation for name: Логическая доска-лабиринт с подставкой "Транспорт"
Done till 265
No translation for name: Каталка-качалка Лошадка Шериф
Done till 266
No translation for name: Каталка-сортер «Черепаха»
Done till 267
No translation for name: Коврик-тренажер Fisher Price «Растем вместе»
Done till 268
No translation for name: Коляска прогулочная UPPAbaby VISTA 2018
Done till 269
No translation for name: Коврик-сумка «Карапуз» без дуг
Done till 270
No translation for name: Коврик Prime Living "Мишка на каникулах/Дороги"
Done till 271
No translation for name: Коврик-синтезатор ELC
Done till 272
No translation for name: Каталка-ходунки Chicco 123
Done till 273
No translation for name: Ксилофон для малышей
Done till 274
No translation for name: Качалка «Мишка»
Done till 275
No translation for name: Каталка на веревочке «Лось-барабанщик»
Done till 276
No translation for name: Каталка-игрушка «Слоник»
Done till 277
No translation for name: Коврик с панелью «Чудесное озеро»
Done till 278
No translation for name: Каталка-ходунки с шариками Battat
Done till 279
No translation for name: Каталка Chicco «Первые шаги»
Done till 280
No translation for name: Качели деревянные к ДСК «Ранний старт»
Done till 281
No translation for name: Качалка «Озорная лошадка»
Done till 282
No translation for name: Качалка «Задорный Конь», Jolly Ride
Done till 283
No translation for name: Каталка Cute Rider "Кошка"
Done till 284
No translation for name: Качалка Little tikes «Полиция»
Done till 285
No translation for name: Коляска прогулочная UPPAbaby MINU 2018
Done till 286
No translation for name: Каталка Cute Rider "Панда"
Done till 287
No translation for name: Коляска-автокресло Chicco Keyfit Caddy
Done till 288
No translation for name: Конструктор магнитный для малышей Grippies 20 дет.
Done till 289
No translation for name: Кольца деревянные гимнастические KIDWOOD
Done till 290
No translation for name: Кроватка Chicco Next2Me
Done till 291

In [ ]:
all_cats = set(df['main_category'].unique())

for cats in df['categories']:
    for x in cats:
        all_cats.add(x)


uniq_main_cats = list(all_cats)
cat_rus_to_eng = {}

for idx,cat in enumerate(uniq_main_cats):
    print(f'Done till {idx}')
    try:
        eng_cat = translator.translate(cat)
        cat_rus_to_eng[cat] = eng_cat
    except Exception as e:
        print(f'No translation for category: {cat}')
        cat_rus_to_eng[cat] = 'No_translation'

In [75]:
df['name_translated'] = df['name'].map(name_rus_to_eng)
df['main_category_translated'] = df['main_category'].map(cat_rus_to_eng)

In [92]:
df['categories_translated'] = df['categories'].apply(lambda x: [cat_rus_to_eng[y] for y in x])

In [93]:
df

,id,name,brand,main_category,categories,slug,name_translated,main_category_translated,categories_translated
0,463480210,Кокон для новорожденных Cocoonababy Red Castle...,Red Castle,Коконы для новорожденных,[],matras-red-castle-kokon-dlya-novorozhdennyh-co...,Cocoon for newborns Cocoonababy Red Castle for...,Cocoons for newborns,[]
1,463480211,Кокон для новорожденных Matello Cocon Baby Lux...,Matello,Коконы для новорожденных,[],kokon-dlya-novorozhdennyh-matello-cocon-baby-l...,Cocoon for newborns Matello Cocon Baby Lux for...,Cocoons for newborns,[]
2,463480212,Кокон-люлька для новорожденных Farla Baby Shel...,Farla,Коконы для новорожденных,[],kokon-lyulka-dlya-novorozhdennyh-farla-baby-sh...,Farla Baby Shell for rent,Cocoons for newborns,[]
3,463480213,Качели-шезлонг 4moms MamaRoo 4.0 напрокат,4moms,Электрокачели,"[Качели, шезлонги]",kacheli-shezlong-4moms-mamaroo-40-naprokat,Swing-chaise lounge 4moms MamaRoo 4.0 for rent,Electric swing,"[Swings, sun loungers]"
4,463480214,Качели-шезлонг 4moms MamaRoo 3.0 напрокат,4moms,Электрокачели,"[Качели, шезлонги]",kacheli-shezlong-4moms-mamaroo-30-naprokat,Swing-chaise lounge 4moms MamaRoo 3.0 for rent,Electric swing,"[Swings, sun loungers]"
...,...,...,...,...,...,...,...,...,...
683,1651502137,Адаптеры для автолюльки Yoyo,BabyZen,Коляски,[],adaptery-dlya-avtolyulki-yoyo,Yoyo Car Seat Adapters,Strollers,[]
684,1655011689,Электрокачели MamaRoo NEW + весы Maman напрокат,Maman##4moms,Акции недели,"[Качели, шезлонги, Весы]",elektrokacheli-mamaroo-new-vesy-maman-naprokat,Electric swing MamaRoo NEW + Maman scales for ...,Promotions of the week,"[Swings, sun loungers, Scales]"
685,1677458905,Обезьянка на кольцах напрокат,Bright Starts,Музыкальные игрушки,[Развивающие игрушки],obezyanka-na-koltsah-naprokat,Ring monkey for rent,Musical toys,[Educational toys]
686,1677460825,"Развивающая игрушка ""Маленькие друзья"" напрокат",Fisher-Price,Музыкальные игрушки,[Развивающие игрушки],razvivayuschaya-igrushka-malenkie-druzya-naprokat,"Educational toy ""Little Friends"" for rent",Musical toys,[Educational toys]
687,1678176625,Манеж-кровать Зебра напрокат,Coto Baby,"Кроватки, манежи",[],manezh-krovat-zebra-naprokat,Playpen-bed Zebra for rent,"Cribs, playpens",[]

In [136]:
def return_string_from_list(list_cats):
    string = ''
    if len(list_cats) != 0:
        string = 'Remaining_Categories: '
        for cat in list_cats:
            string += cat + ', '

    return string

In [138]:
prod_desc = []
for idx, row in df.iterrows():
    string = 'Name: ' + row['name_translated'] + '\n' +  'Main_Category: ' + row['main_category_translated'] + '\n' + return_string_from_list(row['categories_translated'])
    prod_desc.append(string.strip())

In [142]:
df['Description_Translated'] = prod_desc
df

,id,name,brand,main_category,categories,slug,name_translated,main_category_translated,categories_translated,Description_Translated
0,463480210,Кокон для новорожденных Cocoonababy Red Castle...,Red Castle,Коконы для новорожденных,[],matras-red-castle-kokon-dlya-novorozhdennyh-co...,Cocoon for newborns Cocoonababy Red Castle for...,Cocoons for newborns,[],Name: Cocoon for newborns Cocoonababy Red Cast...
1,463480211,Кокон для новорожденных Matello Cocon Baby Lux...,Matello,Коконы для новорожденных,[],kokon-dlya-novorozhdennyh-matello-cocon-baby-l...,Cocoon for newborns Matello Cocon Baby Lux for...,Cocoons for newborns,[],Name: Cocoon for newborns Matello Cocon Baby L...
2,463480212,Кокон-люлька для новорожденных Farla Baby Shel...,Farla,Коконы для новорожденных,[],kokon-lyulka-dlya-novorozhdennyh-farla-baby-sh...,Farla Baby Shell for rent,Cocoons for newborns,[],Name: Farla Baby Shell for rent\nMain_Category...
3,463480213,Качели-шезлонг 4moms MamaRoo 4.0 напрокат,4moms,Электрокачели,"[Качели, шезлонги]",kacheli-shezlong-4moms-mamaroo-40-naprokat,Swing-chaise lounge 4moms MamaRoo 4.0 for rent,Electric swing,"[Swings, sun loungers]",Name: Swing-chaise lounge 4moms MamaRoo 4.0 fo...
4,463480214,Качели-шезлонг 4moms MamaRoo 3.0 напрокат,4moms,Электрокачели,"[Качели, шезлонги]",kacheli-shezlong-4moms-mamaroo-30-naprokat,Swing-chaise lounge 4moms MamaRoo 3.0 for rent,Electric swing,"[Swings, sun loungers]",Name: Swing-chaise lounge 4moms MamaRoo 3.0 fo...
...,...,...,...,...,...,...,...,...,...,...
683,1651502137,Адаптеры для автолюльки Yoyo,BabyZen,Коляски,[],adaptery-dlya-avtolyulki-yoyo,Yoyo Car Seat Adapters,Strollers,[],Name: Yoyo Car Seat Adapters\nMain_Category: S...
684,1655011689,Электрокачели MamaRoo NEW + весы Maman напрокат,Maman##4moms,Акции недели,"[Качели, шезлонги, Весы]",elektrokacheli-mamaroo-new-vesy-maman-naprokat,Electric swing MamaRoo NEW + Maman scales for ...,Promotions of the week,"[Swings, sun loungers, Scales]",Name: Electric swing MamaRoo NEW + Maman scale...
685,1677458905,Обезьянка на кольцах напрокат,Bright Starts,Музыкальные игрушки,[Развивающие игрушки],obezyanka-na-koltsah-naprokat,Ring monkey for rent,Musical toys,[Educational toys],Name: Ring monkey for rent\nMain_Category: Mus...
686,1677460825,"Развивающая игрушка ""Маленькие друзья"" напрокат",Fisher-Price,Музыкальные игрушки,[Развивающие игрушки],razvivayuschaya-igrushka-malenkie-druzya-naprokat,"Educational toy ""Little Friends"" for rent",Musical toys,[Educational toys],"Name: Educational toy ""Little Friends"" for ren..."
687,1678176625,Манеж-кровать Зебра напрокат,Coto Baby,"Кроватки, манежи",[],manezh-krovat-zebra-naprokat,Playpen-bed Zebra for rent,"Cribs, playpens",[],Name: Playpen-bed Zebra for rent\nMain_Categor...

In [143]:
df[['id','Description_Translated']].to_csv('Product_ID_To_Descriptions.csv', index = False)

In [35]:
import json

with open('prod_names_rus_to_eng', 'w') as f:
    json.dump(name_rus_to_eng,f)

In [53]:
with open('prod_cats_rus_to_eng', 'w') as f:
    json.dump(cat_rus_to_eng,f)